# Generated by Django 4.2 on 2023-04-05 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('idCode', models.AutoField(primary_key=True, serialize=False)),
                ('nif', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('lastname1', models.CharField(max_length=100)),
                ('lastname2', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAd', models.DateTimeField(auto_now_add=True)),
                ('idCode_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.department')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['idCode'],
            },
        ),
    ]
